image:
  file: .gitpod/Dockerfile

ports:
  - port: 1337  # Parse Backend from compose
  - port: 4040  # Parse Dashboard from compose
  - port: 8080  # The dev server

tasks:
  - before: .gitpod/boot_containers.sh
  - openMode: tab-after
    command: |
      npm install
      .gitpod/devserver.sh
#    init: |
#      export VUE_APP_PARSE_URL=`(gp url 1337)`
#      npm run dev:db
#      npm run dev:db:mock-data
#      cp .env.development.local.template .env.development.local
#      echo "" >> .env.development
#      echo "VUE_APP_PARSE_URL=`(gp url 8080)`" >> .env.development.local
#    command: npm run serve
#  - command: gp await-port 8080 && gp preview $(gp url 8080)
