image:
  file: .gitpod/Dockerfile

ports:
  - port: 1337  # Parse Backend from compose
  - port: 4040  # Parse Dashboard from compose
  - port: 8080  # The dev server

tasks:
  - command: .gitpod/boot_containers.sh
