image:
  file: .gitpod/Dockerfile

ports:
  - port: 1337  # Parse Backend from compose
  - port: 4040  # Parse Dashboard from compose
  - port: 8000  # The dev server

tasks:
  - before: |
      docker-compose up -d
      npm install
    init: |
      npm run dev:db
      npm run dev:db:mock-data
      cp .env.development.local.template .env.development.local
    command: npm run serve
